version: "3.8"

services:
  service_1:
   build: ./service_1
   container_name: service1 
   expose:
     - "8001"
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
     interval: 30s
     timeout: 5s
     retries: 3
  service_2:
   build: ./service_2
   container_name: service2 
   expose:
     - "8002"
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
     interval: 30s
     timeout: 5s
     retries: 3
  nginx:
   build: ./nginx
   container_name: nginx-proxy
   ports:
    - "8080:80"
   depends_on:
    service_1:
      condition: service_healthy
    service_2:
      condition: service_healthy   
   
